### ISSUE TITLE
Ablaufdiagramm und USE-Case Mediumsverwaltung

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff#10]
dazu gehören:

- [x] Use-Case für Medien-Kollektionen verwalten anlegen

- [x] Verfeinerte Use Cases anlegen
    - [x] Neue Medienkollektion anlegen
    - [x] Vorhandene Medienkollektion bearbeiten

- [x] Ablaufdiagramme für verfeinerte Use Cases erstellen

- [x] Use Case - Medium anlegen
    - [x] Medium allgemein anlegen
    - [x] Neues Buch anlegen
    - [x] Neuen Film anlegen
    - [x] Neue Serie anlegen
    - [x] Neue Episode anlegen
    - [x] Neues Spiel anlegen

**Comment by LittleBigPlaye** [comment]
**Medienkollektionen verwalten**

![medienkollektionen_verwalten](https://user-images.githubusercontent.com/71118367/102486190-f2d8c100-4068-11eb-9ecb-886da39fba55.png)

**Comment by LittleBigPlaye** [comment]
**Neue Medienkollektion anlegen**
![neue_medienkollektion_anlegen](https://user-images.githubusercontent.com/71118367/102487308-a55d5380-406a-11eb-8b5c-ee638b19a421.png)

**Vorhandene Kollektion Bearbeiten**
![vorhandene_kollektion_bearbeiten](https://user-images.githubusercontent.com/71118367/102487426-d63d8880-406a-11eb-80e1-2558a2c1ba71.png)

**Comment by LittleBigPlaye** [comment]
**Neues Medium anlegen**
![java_use_case](https://user-images.githubusercontent.com/71118367/102505464-4e637880-4082-11eb-8418-53bea2a0c7cd.png)

**Comment by LittleBigPlaye** [comment]
**Ablaufdiagramme Medienkollektionen**
![ablaufdiagramme_medienkollektionen](https://user-images.githubusercontent.com/71118367/102506629-9afb8380-4083-11eb-9e93-ae4adb850ecd.png)
