### ISSUE TITLE
Offene Funktionen

### ISSUE THREAD

**Issue by LittleBigPlaye** [fh-erfurt/RateYourStuff#23]
Um nicht aus den Augen zu verlieren, was noch zukünftig getan werden muss, fange ich hier mal eine Liste an. 
Falls noch Ergänzungen / weitere Ideen / Problematiken vorliegen, einfach hier ergänzen:

- [x] Klassen in Packages untergliedern

- [x] Funktionalität: Medien löschen 
(Beinhaltet das Löschen sämtlicher Kommentare, die auf das Medium verweisen und das entfernen aus sämtlichen Kollektionen, die das zu löschende Medium beinhaltet)

- [x] Funktionalität: Medien bearbeiten (An sich eigentlich durch getter und setter geregelt)
- [x] Überlegen, an welchen Stellen Getter / Setter / Adder Sinn machen.
Getter von Listen weichen die Datenkapselung auf, wen z. B. sichergestellt werden soll, dass ein Film nur einmal in der Library vorkommen darf, kann man die Regelung einfach umgehen, indem man sich die Liste aller Medien über den Getter zurückgeben lässt und den Eintrag manuell setzt.

- [x] Überlegen, bei welchen Konstruktoren es Sinn macht ganze Listen zu übergeben. (z. B. ein neuer Nutzer wird nie direkt mit der Registrierung / Anlage direkt Medienkollektionen oder Kommentare haben)

- [x] Die Personen nochmal überdenken 
(Macht es Sinn den Personen zuzuweisen, was sie sind...? Würde den ohnehin schon großen Arbeitsaufwand nur noch mehr erhöhen)

- [x]  Das mit den Genres nochmal überdenken
(Soll wirklich geregelt werden, dass nicht jedes Medium jedes Genre haben kann? - Ebenfalls (geschätzter) sehr hoher Arbeitsaufwand)

**Comment by Avartos** [comment]
Zu den Personen: ICh würde das lassen mit der Zuordnung, denn am Ende ist es einfah nur ein Enum oder mehrere Bools in der Klasse, falls einer Schauspieler, Autor und Regisseur zusammen ist. Im Endeffekt ist das ja kein wirklicher Mehraufwand ein Bool auf true zu setzen und das im Constructor mit aufzunehmen.
MEINE MEINUNG :P :)

**Comment by Avartos** [comment]
Person ein Enum zuweisen anstatt der Bool

**Comment by Avartos** [comment]
Genre als Enum und das dem Medium zuweisen --> nur Hauptgenre
