### ISSUE TITLE
Ablaufdiagramm und USE-Case erstellen für Login

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff#5]
- [x] Ablaufdiagramm erstellen
    - [x] Login
    - [x] Registration 
- [x] USE-Case erstellen

**Comment by TheBirdEffect** [comment]
![LoginUseCase](https://user-images.githubusercontent.com/56632916/102780953-254f2a80-4397-11eb-8059-2e55c7ad5992.png)
![Login_Activity_Dia](https://user-images.githubusercontent.com/56632916/102780961-28e2b180-4397-11eb-9e00-b3123c0be673.png)
![Registry_Activity_Dia](https://user-images.githubusercontent.com/56632916/102780971-2c763880-4397-11eb-93ea-aa6f35d57566.png)

**Comment by TheBirdEffect** [comment]
Hier nochmal die geänderten UseCases für LogIn, gerne nochmal drüberschauen, sollte so aber passen
