### ISSUE TITLE
Ablauf Diagramm und USE-Case für die Benutzerverwaltung

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff#6]
Dazu gehören:

- [x] Freundesliste als Wunschkriterium zu Doku hinzufügen

- [x] USE-Case Benutzerverwaltung
- [x] Aktivitätsdiagramme
    - [x]  Freund zu Freundesliste hinzufügen
    - [x] Passwort ändern
    - [x] Benutzerdaten einsehen
    - [x] Benutzerdaten ändern
    - [x] User sperren
    - [x] User entsperren
    - [x] User zu Moderatoren ernennen
    - [x] User nach Nicknamen finden
    - [x] Passwort zurücksetzen

**Comment by TheBirdEffect** [comment]
##Benutzerverwaltung UseCases + Aktivitätsdiagramme
![UseCase](https://user-images.githubusercontent.com/56632916/102818146-5f3d2280-43d1-11eb-988e-651a8ffc9fed.png)
![viewUserData](https://user-images.githubusercontent.com/56632916/102818154-65330380-43d1-11eb-8999-c21287036557.png)
![addFriend](https://user-images.githubusercontent.com/56632916/102818157-66643080-43d1-11eb-9ea2-ae49224119af.png)
![changePassword](https://user-images.githubusercontent.com/56632916/102818160-66fcc700-43d1-11eb-8de7-390fcf75e24f.png)
![changeUserData](https://user-images.githubusercontent.com/56632916/102818161-66fcc700-43d1-11eb-8309-bfd43daa2d6b.png)
![disableUser](https://user-images.githubusercontent.com/56632916/102818163-66fcc700-43d1-11eb-8c85-fcf250c42f01.png)
![enableMod](https://user-images.githubusercontent.com/56632916/102818164-67955d80-43d1-11eb-8c12-d235930b0a7d.png)
![enableUser](https://user-images.githubusercontent.com/56632916/102818165-67955d80-43d1-11eb-9a44-9fb5861606d4.png)
![findUserByName](https://user-images.githubusercontent.com/56632916/102818166-682df400-43d1-11eb-9c2d-c5ef5d04ca42.png)
![isValidUser](https://user-images.githubusercontent.com/56632916/102818168-682df400-43d1-11eb-8fbb-feb4bfa1f99c.png)
![setPasswordToDefault](https://user-images.githubusercontent.com/56632916/102818169-682df400-43d1-11eb-8d01-d132c59a63f3.png)
