### ISSUE TITLE
Ablaufdiagramm und USE-Case für die Mediensuche

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff#7]
- [x] Ablaufdiagramm erstellen
- [x] USE-Case erstellen
- [x] es RICHTIG machen

**Comment by MKnop2** [comment]
![image](https://user-images.githubusercontent.com/56631092/103337758-9ae48600-4a7c-11eb-9956-b46279ee76f9.png)

hier jetzt auch meine updated Version der Mediensuche, korrekturen evtl. noch nötig wenn die toString Funktion hierbei berücksichtigt werden muss? (rücksprache mit Robin nötig)
