### ISSUE TITLE
Ablaufdiagramm und USE-Case für die Kommentarverwaltung

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff#8]
Dazu gehören:

- [x] USE-Case Kommentar anlegen
- [x] Ablaufdiagramme
- [x]  Ablaufdiagramm delete()

**Comment by MKnop2** [comment]
![image](https://user-images.githubusercontent.com/56631092/103337924-07f81b80-4a7d-11eb-9768-512540d2bfad.png)

![image](https://user-images.githubusercontent.com/56631092/103337936-10e8ed00-4a7d-11eb-9246-2d3b5640c7a8.png)


neuste Version der Kommentarverwaltung, müsste jetzt so passen, dennoch drüber schauen erwünscht.
