### ISSUE TITLE
Ablaufdiagramm und USE-Case Fortschrittverwaltung

### ISSUE THREAD

**Issue by Avartos** [fh-erfurt/RateYourStuff#9]
Dazu gehören:

- [x] Use-Case für das Anlegen eines neuen Fortschritts

- [x] Ablaufdiagramm für das Anlegen eines neuen Fortschritts

- [x] Wunschkriterium "Nach Fortschritt filtern" zu Doku hinzufügen

**Comment by LittleBigPlaye** [comment]
**Use-Case - Fortschritt anlegen**

![usecase_fortschritt_anlegen](https://user-images.githubusercontent.com/71118367/102483413-ff5b1a80-4064-11eb-9eaa-b8abf8dcde3a.png)

**Comment by LittleBigPlaye** [comment]
**Ablaufdiagramm: Fortschritt anlegen**

![ablaufdiagramm_fortschritt_anlegen](https://user-images.githubusercontent.com/71118367/102485076-6aa5ec00-4067-11eb-8d7d-a04649e59a4d.png)

**Comment by LittleBigPlaye** [comment]
![2021-01-26 09_04_15-Window](https://user-images.githubusercontent.com/71118367/105817323-c1330e00-5fb5-11eb-92b6-94ea9f3a79c2.png)
![2021-01-26 09_04_27-Window](https://user-images.githubusercontent.com/71118367/105817327-c2fcd180-5fb5-11eb-9a6c-d4e0c8b9c9dd.png)
![2021-01-26 09_04_32-Window](https://user-images.githubusercontent.com/71118367/105817328-c3956800-5fb5-11eb-8ca4-c150dd8564f8.png)
![2021-01-26 09_04_37-Window](https://user-images.githubusercontent.com/71118367/105817330-c3956800-5fb5-11eb-96c6-d554d37ec086.png)
![2021-01-26 09_04_41-Window](https://user-images.githubusercontent.com/71118367/105817331-c42dfe80-5fb5-11eb-9d12-d17c7b9ed610.png)
![2021-01-26 09_02_27-Window](https://user-images.githubusercontent.com/71118367/105817333-c55f2b80-5fb5-11eb-8f0a-b00e6bf0ec16.png)
![2021-01-26 09_02_32-Window](https://user-images.githubusercontent.com/71118367/105817334-c55f2b80-5fb5-11eb-97a8-f803c8de4a5a.png)
![2021-01-26 09_02_56-Window](https://user-images.githubusercontent.com/71118367/105817335-c5f7c200-5fb5-11eb-8921-caf694b492f7.png)
![2021-01-26 09_03_04-Window](https://user-images.githubusercontent.com/71118367/105817337-c6905880-5fb5-11eb-820f-2ba352946ed8.png)
![2021-01-26 09_03_08-Window](https://user-images.githubusercontent.com/71118367/105817341-c728ef00-5fb5-11eb-989c-9e1b4ec59b43.png)
![2021-01-26 09_03_13-Window](https://user-images.githubusercontent.com/71118367/105817343-c7c18580-5fb5-11eb-81f4-0b9f9b49c15d.png)
![2021-01-26 09_03_28-Window](https://user-images.githubusercontent.com/71118367/105817344-c7c18580-5fb5-11eb-8202-40acbe244e5e.png)
![2021-01-26 09_03_35-Window](https://user-images.githubusercontent.com/71118367/105817348-c85a1c00-5fb5-11eb-9e25-320fa124ca68.png)
![2021-01-26 09_03_44-Window](https://user-images.githubusercontent.com/71118367/105817352-c8f2b280-5fb5-11eb-95c2-85281a2a9bd1.png)
![2021-01-26 09_03_53-Window](https://user-images.githubusercontent.com/71118367/105817356-c98b4900-5fb5-11eb-8606-891ce5ab54f8.png)
![2021-01-26 09_04_00-Window](https://user-images.githubusercontent.com/71118367/105817359-ca23df80-5fb5-11eb-8515-c8fe32300565.png)
![2021-01-26 09_04_08-Window](https://user-images.githubusercontent.com/71118367/105817360-cabc7600-5fb5-11eb-8612-bd4592c584ff.png)
